#!/bin/bash

# macOS defaults settings exported on Wed May  7 16:32:47 PDT 2025
# Run this script on a new machine to apply your preferred settings


# com.apple.dock settings

defaults write "com.apple.dock" "autohide" 1
defaults write "com.apple.dock" "expose-group-apps" 0
defaults write "com.apple.dock" "last-analytics-stamp" (
defaults write "com.apple.dock" "lastShowIndicatorTime" "768286229.4938329"
defaults write "com.apple.dock" "loc" "en_US:US"
defaults write "com.apple.dock" "minimize-to-application" 0
defaults write "com.apple.dock" "mod-count" 659
defaults write "com.apple.dock" "orientation" bottom
defaults write "com.apple.dock" "persistent-apps" (
defaults write "com.apple.dock" "GUID" 2217543806
defaults write "com.apple.dock" "tile-data" {
defaults write "com.apple.dock" "book" {length 708, bytes 0x626f6f6b c4020000 00000410 30000000 ... 04000000 00000000 }
defaults write "com.apple.dock" "bundle-identifier" "com.apple.Safari.WebApp.5A87696C-CA1E-48AD-A591-3116081C4116"
defaults write "com.apple.dock" "dock-extra" 0
defaults write "com.apple.dock" "file-data" {
defaults write "com.apple.dock" "_CFURLString" "file:///Users/jayvicsanantonio/Applications/Gemini.app/"
defaults write "com.apple.dock" "_CFURLStringType" 15
defaults write "com.apple.dock" "file-label" Gemini
defaults write "com.apple.dock" "file-mod-date" 88239636272177
defaults write "com.apple.dock" "file-type" 41
defaults write "com.apple.dock" "is-beta" 0
defaults write "com.apple.dock" "parent-mod-date" 52329414710321
defaults write "com.apple.dock" "tile-type" "file-tile"
defaults write "com.apple.dock" "GUID" 1145402576
defaults write "com.apple.dock" "tile-data" {
defaults write "com.apple.dock" "book" {length 556, bytes 0x626f6f6b 2c020000 00000410 30000000 ... 04000000 00000000 }
defaults write "com.apple.dock" "bundle-identifier" "com.openai.chat"
defaults write "com.apple.dock" "dock-extra" 0
defaults write "com.apple.dock" "file-data" {
defaults write "com.apple.dock" "_CFURLString" "file:///Applications/ChatGPT.app/"
defaults write "com.apple.dock" "_CFURLStringType" 15
defaults write "com.apple.dock" "file-label" ChatGPT
defaults write "com.apple.dock" "file-mod-date" 114417462609205
defaults write "com.apple.dock" "file-type" 41
defaults write "com.apple.dock" "is-beta" 0
defaults write "com.apple.dock" "parent-mod-date" 30188859604353
defaults write "com.apple.dock" "tile-type" "file-tile"
defaults write "com.apple.dock" "GUID" 1145402574
defaults write "com.apple.dock" "tile-data" {
defaults write "com.apple.dock" "book" {length 560, bytes 0x626f6f6b 30020000 00000410 30000000 ... 04000000 00000000 }
defaults write "com.apple.dock" "bundle-identifier" "ai.perplexity.mac"
defaults write "com.apple.dock" "dock-extra" 0
defaults write "com.apple.dock" "file-data" {
defaults write "com.apple.dock" "_CFURLString" "file:///Applications/Perplexity.app/"
defaults write "com.apple.dock" "_CFURLStringType" 15
defaults write "com.apple.dock" "file-label" Perplexity
defaults write "com.apple.dock" "file-mod-date" 70243723559565
defaults write "com.apple.dock" "file-type" 1
defaults write "com.apple.dock" "is-beta" 0
defaults write "com.apple.dock" "parent-mod-date" 50542708668357
defaults write "com.apple.dock" "tile-type" "file-tile"
defaults write "com.apple.dock" "GUID" 1145402559
defaults write "com.apple.dock" "tile-data" {
defaults write "com.apple.dock" "book" {length 556, bytes 0x626f6f6b 2c020000 00000410 30000000 ... 04000000 00000000 }
defaults write "com.apple.dock" "bundle-identifier" "com.anthropic.claudefordesktop"
defaults write "com.apple.dock" "dock-extra" 0
defaults write "com.apple.dock" "file-data" {
defaults write "com.apple.dock" "_CFURLString" "file:///Applications/Claude.app/"
defaults write "com.apple.dock" "_CFURLStringType" 15
defaults write "com.apple.dock" "file-label" Claude
defaults write "com.apple.dock" "file-mod-date" 3827069397
defaults write "com.apple.dock" "file-type" 1
defaults write "com.apple.dock" "is-beta" 0
defaults write "com.apple.dock" "parent-mod-date" 50542708668357
defaults write "com.apple.dock" "tile-type" "file-tile"
defaults write "com.apple.dock" "GUID" 2765430425
defaults write "com.apple.dock" "tile-data" {
defaults write "com.apple.dock" "book" {length 564, bytes 0x626f6f6b 34020000 00000410 30000000 ... 04000000 00000000 }
defaults write "com.apple.dock" "bundle-identifier" "com.google.Chrome"
defaults write "com.apple.dock" "dock-extra" 0
defaults write "com.apple.dock" "file-data" {
defaults write "com.apple.dock" "_CFURLString" "file:///Applications/Google%20Chrome.app/"
defaults write "com.apple.dock" "_CFURLStringType" 15
defaults write "com.apple.dock" "file-label" "Google Chrome"
defaults write "com.apple.dock" "file-mod-date" 196472812364890
defaults write "com.apple.dock" "file-type" 41
defaults write "com.apple.dock" "is-beta" 0
defaults write "com.apple.dock" "parent-mod-date" 149485870958661
defaults write "com.apple.dock" "tile-type" "file-tile"
defaults write "com.apple.dock" "GUID" 4209011283
defaults write "com.apple.dock" "tile-data" {
defaults write "com.apple.dock" "book" {length 580, bytes 0x626f6f6b 44020000 00000410 30000000 ... 04000000 00000000 }
defaults write "com.apple.dock" "bundle-identifier" "com.apple.MobileSMS"
defaults write "com.apple.dock" "dock-extra" 0
defaults write "com.apple.dock" "file-data" {
defaults write "com.apple.dock" "_CFURLString" "file:///System/Applications/Messages.app/"
defaults write "com.apple.dock" "_CFURLStringType" 15
defaults write "com.apple.dock" "file-label" Messages
defaults write "com.apple.dock" "file-mod-date" 3827279769
defaults write "com.apple.dock" "file-type" 41
defaults write "com.apple.dock" "is-beta" 0
defaults write "com.apple.dock" "parent-mod-date" 3827279769
defaults write "com.apple.dock" "tile-type" "file-tile"
defaults write "com.apple.dock" "GUID" 4209011284
defaults write "com.apple.dock" "tile-data" {
defaults write "com.apple.dock" "book" {length 576, bytes 0x626f6f6b 40020000 00000410 30000000 ... 04000000 00000000 }
defaults write "com.apple.dock" "bundle-identifier" "com.apple.mail"
defaults write "com.apple.dock" "dock-extra" 0
defaults write "com.apple.dock" "file-data" {
defaults write "com.apple.dock" "_CFURLString" "file:///System/Applications/Mail.app/"
defaults write "com.apple.dock" "_CFURLStringType" 15
defaults write "com.apple.dock" "file-label" Mail
defaults write "com.apple.dock" "file-mod-date" 3827279769
defaults write "com.apple.dock" "file-type" 41
defaults write "com.apple.dock" "is-beta" 0
defaults write "com.apple.dock" "parent-mod-date" 3827279769
defaults write "com.apple.dock" "tile-type" "file-tile"
defaults write "com.apple.dock" "GUID" 4209011286
defaults write "com.apple.dock" "tile-data" {
defaults write "com.apple.dock" "book" {length 580, bytes 0x626f6f6b 44020000 00000410 30000000 ... 04000000 00000000 }
defaults write "com.apple.dock" "bundle-identifier" "com.apple.Photos"
defaults write "com.apple.dock" "dock-extra" 0
defaults write "com.apple.dock" "file-data" {
defaults write "com.apple.dock" "_CFURLString" "file:///System/Applications/Photos.app/"
defaults write "com.apple.dock" "_CFURLStringType" 15
defaults write "com.apple.dock" "file-label" Photos
defaults write "com.apple.dock" "file-mod-date" 3827279769
defaults write "com.apple.dock" "file-type" 41
defaults write "com.apple.dock" "is-beta" 0
defaults write "com.apple.dock" "parent-mod-date" 3827279769
defaults write "com.apple.dock" "tile-type" "file-tile"
defaults write "com.apple.dock" "GUID" 2217543805
defaults write "com.apple.dock" "tile-data" {
defaults write "com.apple.dock" "book" {length 708, bytes 0x626f6f6b c4020000 00000410 30000000 ... 04000000 00000000 }
defaults write "com.apple.dock" "bundle-identifier" "com.apple.Safari.WebApp.8DB0FE23-D277-412A-A50C-D821D4409BCD"
defaults write "com.apple.dock" "dock-extra" 0
defaults write "com.apple.dock" "file-data" {
defaults write "com.apple.dock" "_CFURLString" "file:///Users/jayvicsanantonio/Applications/YouTube.app/"
defaults write "com.apple.dock" "_CFURLStringType" 15
defaults write "com.apple.dock" "file-label" YouTube
defaults write "com.apple.dock" "file-mod-date" 123703181235194
defaults write "com.apple.dock" "file-type" 41
defaults write "com.apple.dock" "is-beta" 0
defaults write "com.apple.dock" "parent-mod-date" 228186851259285
defaults write "com.apple.dock" "tile-type" "file-tile"
defaults write "com.apple.dock" "GUID" 1145402568
defaults write "com.apple.dock" "tile-data" {
defaults write "com.apple.dock" "book" {length 556, bytes 0x626f6f6b 2c020000 00000410 30000000 ... 04000000 00000000 }
defaults write "com.apple.dock" "bundle-identifier" "com.exafunction.windsurf"
defaults write "com.apple.dock" "dock-extra" 0
defaults write "com.apple.dock" "file-data" {
defaults write "com.apple.dock" "_CFURLString" "file:///Applications/Windsurf.app/"
defaults write "com.apple.dock" "_CFURLStringType" 15
defaults write "com.apple.dock" "file-label" Windsurf
defaults write "com.apple.dock" "file-mod-date" 3828388042
defaults write "com.apple.dock" "file-type" 1
defaults write "com.apple.dock" "is-beta" 0
defaults write "com.apple.dock" "parent-mod-date" 50542708668357
defaults write "com.apple.dock" "tile-type" "file-tile"
defaults write "com.apple.dock" "GUID" 3335933869
defaults write "com.apple.dock" "tile-data" {
defaults write "com.apple.dock" "book" {length 708, bytes 0x626f6f6b c4020000 00000410 30000000 ... 04000000 00000000 }
defaults write "com.apple.dock" "bundle-identifier" "com.apple.Safari.WebApp.7903B463-4985-43DA-AA30-7CBC0FB0A935"
defaults write "com.apple.dock" "dock-extra" 0
defaults write "com.apple.dock" "file-data" {
defaults write "com.apple.dock" "_CFURLString" "file:///Users/jayvicsanantonio/Applications/GitHub.app/"
defaults write "com.apple.dock" "_CFURLStringType" 15
defaults write "com.apple.dock" "file-label" GitHub
defaults write "com.apple.dock" "file-mod-date" 37571907243481
defaults write "com.apple.dock" "file-type" 41
defaults write "com.apple.dock" "is-beta" 0
defaults write "com.apple.dock" "parent-mod-date" 19133612641753
defaults write "com.apple.dock" "tile-type" "file-tile"
defaults write "com.apple.dock" "GUID" 3809826292
defaults write "com.apple.dock" "tile-data" {
defaults write "com.apple.dock" "book" {length 1120, bytes 0x626f6f6b 60040000 00000410 30000000 ... 04000000 00000000 }
defaults write "com.apple.dock" "bundle-identifier" "com.apple.Safari"
defaults write "com.apple.dock" "dock-extra" 0
defaults write "com.apple.dock" "file-data" {
defaults write "com.apple.dock" "_CFURLString" "file:///System/Volumes/Preboot/Cryptexes/App/System/Applications/Safari.app/"
defaults write "com.apple.dock" "_CFURLStringType" 15
defaults write "com.apple.dock" "file-label" Safari
defaults write "com.apple.dock" "file-mod-date" 0
defaults write "com.apple.dock" "file-type" 1
defaults write "com.apple.dock" "is-beta" 0
defaults write "com.apple.dock" "parent-mod-date" 0
defaults write "com.apple.dock" "tile-type" "file-tile"
defaults write "com.apple.dock" "GUID" 4209011300
defaults write "com.apple.dock" "tile-data" {
defaults write "com.apple.dock" "book" {length 588, bytes 0x626f6f6b 4c020000 00000410 30000000 ... 04000000 00000000 }
defaults write "com.apple.dock" "bundle-identifier" "com.apple.systempreferences"
defaults write "com.apple.dock" "dock-extra" 1
defaults write "com.apple.dock" "file-data" {
defaults write "com.apple.dock" "_CFURLString" "file:///System/Applications/System%20Settings.app/"
defaults write "com.apple.dock" "_CFURLStringType" 15
defaults write "com.apple.dock" "file-label" "System Settings"
defaults write "com.apple.dock" "file-mod-date" 3827279769
defaults write "com.apple.dock" "file-type" 41
defaults write "com.apple.dock" "is-beta" 0
defaults write "com.apple.dock" "parent-mod-date" 3827279769
defaults write "com.apple.dock" "tile-type" "file-tile"
defaults write "com.apple.dock" "persistent-others" (
defaults write "com.apple.dock" "recent-apps" (
defaults write "com.apple.dock" "GUID" 1371233697
defaults write "com.apple.dock" "tile-data" {
defaults write "com.apple.dock" "book" {length 584, bytes 0x626f6f6b 48020000 00000410 30000000 ... 04000000 00000000 }
defaults write "com.apple.dock" "bundle-identifier" "com.apple.Passwords"
defaults write "com.apple.dock" "dock-extra" 0
defaults write "com.apple.dock" "file-data" {
defaults write "com.apple.dock" "_CFURLString" "file:///System/Applications/Passwords.app/"
defaults write "com.apple.dock" "_CFURLStringType" 15
defaults write "com.apple.dock" "file-label" Passwords
defaults write "com.apple.dock" "file-mod-date" 3827279769
defaults write "com.apple.dock" "file-type" 1
defaults write "com.apple.dock" "is-beta" 0
defaults write "com.apple.dock" "parent-mod-date" 3827279769
defaults write "com.apple.dock" "tile-type" "file-tile"
defaults write "com.apple.dock" "GUID" 1371233698
defaults write "com.apple.dock" "tile-data" {
defaults write "com.apple.dock" "book" {length 568, bytes 0x626f6f6b 38020000 00000410 30000000 ... 04000000 00000000 }
defaults write "com.apple.dock" "bundle-identifier" "com.microsoft.VSCode"
defaults write "com.apple.dock" "dock-extra" 0
defaults write "com.apple.dock" "file-data" {
defaults write "com.apple.dock" "_CFURLString" "file:///Applications/Visual%20Studio%20Code.app/"
defaults write "com.apple.dock" "_CFURLStringType" 15
defaults write "com.apple.dock" "file-label" "Visual Studio Code"
defaults write "com.apple.dock" "file-mod-date" 3827631708
defaults write "com.apple.dock" "file-type" 1
defaults write "com.apple.dock" "is-beta" 0
defaults write "com.apple.dock" "parent-mod-date" 30188859604353
defaults write "com.apple.dock" "tile-type" "file-tile"
defaults write "com.apple.dock" "GUID" 1371233702
defaults write "com.apple.dock" "tile-data" {
defaults write "com.apple.dock" "book" {length 552, bytes 0x626f6f6b 28020000 00000410 30000000 ... 04000000 00000000 }
defaults write "com.apple.dock" "bundle-identifier" "dev.warp.Warp-Stable"
defaults write "com.apple.dock" "dock-extra" 1
defaults write "com.apple.dock" "file-data" {
defaults write "com.apple.dock" "_CFURLString" "file:///Applications/Warp.app/"
defaults write "com.apple.dock" "_CFURLStringType" 15
defaults write "com.apple.dock" "file-label" Warp
defaults write "com.apple.dock" "file-mod-date" 51113940259262
defaults write "com.apple.dock" "file-type" 1
defaults write "com.apple.dock" "is-beta" 0
defaults write "com.apple.dock" "parent-mod-date" 48635744195243
defaults write "com.apple.dock" "tile-type" "file-tile"
defaults write "com.apple.dock" "region" US
defaults write "com.apple.dock" "showAppExposeGestureEnabled" 0
defaults write "com.apple.dock" "ilesize" 76
defaults write "com.apple.dock" "trash-full" 1
defaults write "com.apple.dock" "version" 1
defaults write "com.apple.dock" "wvous-br-corner" 14
defaults write "com.apple.dock" "wvous-tr-corner" 10
defaults write "com.apple.dock" "wvous-tr-modifier" 0

# com.apple.finder settings

defaults write "com.apple.finder" "AppleShowAllFiles" 0
defaults write "com.apple.finder" "CopyProgressWindowLocation" "{664, 287}"
defaults write "com.apple.finder" "DataSeparatedDisplayNameCache" ""
defaults write "com.apple.finder" "DesktopViewSettings" {
defaults write "com.apple.finder" "IconViewSettings" {
defaults write "com.apple.finder" "arrangeBy" none
defaults write "com.apple.finder" "backgroundColorBlue" 1
defaults write "com.apple.finder" "backgroundColorGreen" 1
defaults write "com.apple.finder" "backgroundColorRed" 1
defaults write "com.apple.finder" "backgroundType" 0
defaults write "com.apple.finder" "gridOffsetX" 0
defaults write "com.apple.finder" "gridOffsetY" 0
defaults write "com.apple.finder" "gridSpacing" 54
defaults write "com.apple.finder" "iconSize" 64
defaults write "com.apple.finder" "labelOnBottom" 1
defaults write "com.apple.finder" "showIconPreview" 1
defaults write "com.apple.finder" "showItemInfo" 0
defaults write "com.apple.finder" "extSize" 12
defaults write "com.apple.finder" "viewOptionsVersion" 1
defaults write "com.apple.finder" "DownloadsFolderListViewSettingsVersion" 1
defaults write "com.apple.finder" "EmptyTrashProgressWindowLocation" "{664, 292}"
defaults write "com.apple.finder" "FK_AppCentricShowSidebar" 1
defaults write "com.apple.finder" "FK_DefaultIconViewSettings" {
defaults write "com.apple.finder" "arrangeBy" name
defaults write "com.apple.finder" "backgroundColorBlue" 1
defaults write "com.apple.finder" "backgroundColorGreen" 1
defaults write "com.apple.finder" "backgroundColorRed" 1
defaults write "com.apple.finder" "backgroundType" 0
defaults write "com.apple.finder" "gridOffsetX" 0
defaults write "com.apple.finder" "gridOffsetY" 0
defaults write "com.apple.finder" "gridSpacing" 54
defaults write "com.apple.finder" "iconSize" 64
defaults write "com.apple.finder" "labelOnBottom" 1
defaults write "com.apple.finder" "showIconPreview" 1
defaults write "com.apple.finder" "showItemInfo" 1
defaults write "com.apple.finder" "extSize" 12
defaults write "com.apple.finder" "viewOptionsVersion" 1
defaults write "com.apple.finder" "FK_DefaultListViewSettings" {
defaults write "com.apple.finder" "calculateAllSizes" 0
defaults write "com.apple.finder" "columns" (
defaults write "com.apple.finder" "ascending" 1
defaults write "com.apple.finder" "identifier" name
defaults write "com.apple.finder" "visible" 1
defaults write "com.apple.finder" "width" 300
defaults write "com.apple.finder" "ascending" 0
defaults write "com.apple.finder" "identifier" dateModified
defaults write "com.apple.finder" "visible" 0
defaults write "com.apple.finder" "width" 181
defaults write "com.apple.finder" "ascending" 0
defaults write "com.apple.finder" "identifier" dateCreated
defaults write "com.apple.finder" "visible" 0
defaults write "com.apple.finder" "width" 181
defaults write "com.apple.finder" "ascending" 0
defaults write "com.apple.finder" "identifier" size
defaults write "com.apple.finder" "visible" 1
defaults write "com.apple.finder" "width" 97
defaults write "com.apple.finder" "ascending" 1
defaults write "com.apple.finder" "identifier" kind
defaults write "com.apple.finder" "visible" 1
defaults write "com.apple.finder" "width" 115
defaults write "com.apple.finder" "ascending" 1
defaults write "com.apple.finder" "identifier" label
defaults write "com.apple.finder" "visible" 0
defaults write "com.apple.finder" "width" 100
defaults write "com.apple.finder" "ascending" 1
defaults write "com.apple.finder" "identifier" version
defaults write "com.apple.finder" "visible" 0
defaults write "com.apple.finder" "width" 75
defaults write "com.apple.finder" "ascending" 1
defaults write "com.apple.finder" "identifier" comments
defaults write "com.apple.finder" "visible" 0
defaults write "com.apple.finder" "width" 300
defaults write "com.apple.finder" "ascending" 0
defaults write "com.apple.finder" "identifier" dateLastOpened
defaults write "com.apple.finder" "visible" 0
defaults write "com.apple.finder" "width" 200
defaults write "com.apple.finder" "ascending" 0
defaults write "com.apple.finder" "identifier" shareOwner
defaults write "com.apple.finder" "visible" 0
defaults write "com.apple.finder" "width" 200
defaults write "com.apple.finder" "ascending" 0
defaults write "com.apple.finder" "identifier" shareLastEditor
defaults write "com.apple.finder" "visible" 0
defaults write "com.apple.finder" "width" 200
defaults write "com.apple.finder" "ascending" 0
defaults write "com.apple.finder" "identifier" dateAdded
defaults write "com.apple.finder" "visible" 1
defaults write "com.apple.finder" "width" 181
defaults write "com.apple.finder" "iconSize" 16
defaults write "com.apple.finder" "showIconPreview" 1
defaults write "com.apple.finder" "sortColumn" dateAdded
defaults write "com.apple.finder" "extSize" 13
defaults write "com.apple.finder" "useRelativeDates" 1
defaults write "com.apple.finder" "viewOptionsVersion" 1
defaults write "com.apple.finder" "FK_SidebarWidth" 167
defaults write "com.apple.finder" "FK_StandardViewOptions2" {
defaults write "com.apple.finder" "ColumnViewOptions" {
defaults write "com.apple.finder" "ArrangeBy" dnam
defaults write "com.apple.finder" "ColumnShowFolderArrow" 1
defaults write "com.apple.finder" "ColumnShowIcons" 1
defaults write "com.apple.finder" "ColumnWidth" 245
defaults write "com.apple.finder" "FontSize" 13
defaults write "com.apple.finder" "PreviewDisclosureState" 1
defaults write "com.apple.finder" "SharedArrangeBy" kipl
defaults write "com.apple.finder" "ShowIconThumbnails" 1
defaults write "com.apple.finder" "ShowPreview" 1
defaults write "com.apple.finder" "FK_StandardViewSettings" {
defaults write "com.apple.finder" "ExtendedListViewSettingsV2" {
defaults write "com.apple.finder" "calculateAllSizes" 0
defaults write "com.apple.finder" "columns" (
defaults write "com.apple.finder" "ascending" 1
defaults write "com.apple.finder" "identifier" name
defaults write "com.apple.finder" "visible" 1
defaults write "com.apple.finder" "width" 300
defaults write "com.apple.finder" "ascending" 0
defaults write "com.apple.finder" "identifier" dateModified
defaults write "com.apple.finder" "visible" 1
defaults write "com.apple.finder" "width" 181
defaults write "com.apple.finder" "ascending" 0
defaults write "com.apple.finder" "identifier" dateCreated
defaults write "com.apple.finder" "visible" 0
defaults write "com.apple.finder" "width" 181
defaults write "com.apple.finder" "ascending" 0
defaults write "com.apple.finder" "identifier" size
defaults write "com.apple.finder" "visible" 1
defaults write "com.apple.finder" "width" 97
defaults write "com.apple.finder" "ascending" 1
defaults write "com.apple.finder" "identifier" kind
defaults write "com.apple.finder" "visible" 1
defaults write "com.apple.finder" "width" 115
defaults write "com.apple.finder" "ascending" 1
defaults write "com.apple.finder" "identifier" label
defaults write "com.apple.finder" "visible" 0
defaults write "com.apple.finder" "width" 100
defaults write "com.apple.finder" "ascending" 1
defaults write "com.apple.finder" "identifier" version
defaults write "com.apple.finder" "visible" 0
defaults write "com.apple.finder" "width" 75
defaults write "com.apple.finder" "ascending" 1
defaults write "com.apple.finder" "identifier" comments
defaults write "com.apple.finder" "visible" 0
defaults write "com.apple.finder" "width" 300
defaults write "com.apple.finder" "ascending" 0
defaults write "com.apple.finder" "identifier" dateLastOpened
defaults write "com.apple.finder" "visible" 0
defaults write "com.apple.finder" "width" 200
defaults write "com.apple.finder" "ascending" 0
defaults write "com.apple.finder" "identifier" shareOwner
defaults write "com.apple.finder" "visible" 0
defaults write "com.apple.finder" "width" 200
defaults write "com.apple.finder" "ascending" 0
defaults write "com.apple.finder" "identifier" shareLastEditor
defaults write "com.apple.finder" "visible" 0
defaults write "com.apple.finder" "width" 200
defaults write "com.apple.finder" "iconSize" 16
defaults write "com.apple.finder" "showIconPreview" 1
defaults write "com.apple.finder" "sortColumn" name
defaults write "com.apple.finder" "extSize" 13
defaults write "com.apple.finder" "useRelativeDates" 1
defaults write "com.apple.finder" "viewOptionsVersion" 1
defaults write "com.apple.finder" "IconViewSettings" {
defaults write "com.apple.finder" "arrangeBy" none
defaults write "com.apple.finder" "backgroundColorBlue" 1
defaults write "com.apple.finder" "backgroundColorGreen" 1
defaults write "com.apple.finder" "backgroundColorRed" 1
defaults write "com.apple.finder" "backgroundType" 0
defaults write "com.apple.finder" "gridOffsetX" 0
defaults write "com.apple.finder" "gridOffsetY" 0
defaults write "com.apple.finder" "gridSpacing" 54
defaults write "com.apple.finder" "iconSize" 64
defaults write "com.apple.finder" "labelOnBottom" 1
defaults write "com.apple.finder" "showIconPreview" 1
defaults write "com.apple.finder" "showItemInfo" 0
defaults write "com.apple.finder" "extSize" 12
defaults write "com.apple.finder" "viewOptionsVersion" 1
defaults write "com.apple.finder" "ListViewSettings" {
defaults write "com.apple.finder" "calculateAllSizes" 0
defaults write "com.apple.finder" "columns" {
defaults write "com.apple.finder" "comments" {
defaults write "com.apple.finder" "ascending" 1
defaults write "com.apple.finder" "index" 7
defaults write "com.apple.finder" "visible" 0
defaults write "com.apple.finder" "width" 300
defaults write "com.apple.finder" "dateCreated" {
defaults write "com.apple.finder" "ascending" 0
defaults write "com.apple.finder" "index" 2
defaults write "com.apple.finder" "visible" 0
defaults write "com.apple.finder" "width" 181
defaults write "com.apple.finder" "dateLastOpened" {
defaults write "com.apple.finder" "ascending" 0
defaults write "com.apple.finder" "index" 8
defaults write "com.apple.finder" "visible" 0
defaults write "com.apple.finder" "width" 200
defaults write "com.apple.finder" "dateModified" {
defaults write "com.apple.finder" "ascending" 0
defaults write "com.apple.finder" "index" 1
defaults write "com.apple.finder" "visible" 1
defaults write "com.apple.finder" "width" 181
defaults write "com.apple.finder" "kind" {
defaults write "com.apple.finder" "ascending" 1
defaults write "com.apple.finder" "index" 4
defaults write "com.apple.finder" "visible" 1
defaults write "com.apple.finder" "width" 115
defaults write "com.apple.finder" "label" {
defaults write "com.apple.finder" "ascending" 1
defaults write "com.apple.finder" "index" 5
defaults write "com.apple.finder" "visible" 0
defaults write "com.apple.finder" "width" 100
defaults write "com.apple.finder" "name" {
defaults write "com.apple.finder" "ascending" 1
defaults write "com.apple.finder" "index" 0
defaults write "com.apple.finder" "visible" 1
defaults write "com.apple.finder" "width" 300
defaults write "com.apple.finder" "size" {
defaults write "com.apple.finder" "ascending" 0
defaults write "com.apple.finder" "index" 3
defaults write "com.apple.finder" "visible" 1
defaults write "com.apple.finder" "width" 97
defaults write "com.apple.finder" "version" {
defaults write "com.apple.finder" "ascending" 1
defaults write "com.apple.finder" "index" 6
defaults write "com.apple.finder" "visible" 0
defaults write "com.apple.finder" "width" 75
defaults write "com.apple.finder" "iconSize" 16
defaults write "com.apple.finder" "showIconPreview" 1
defaults write "com.apple.finder" "sortColumn" name
defaults write "com.apple.finder" "extSize" 13
defaults write "com.apple.finder" "useRelativeDates" 1
defaults write "com.apple.finder" "viewOptionsVersion" 1
defaults write "com.apple.finder" "SettingsType" "FK_StandardViewSettings"
defaults write "com.apple.finder" "FXArrangeGroupViewBy" Name
defaults write "com.apple.finder" "FXDefaultSearchScope" SCcf
defaults write "com.apple.finder" "FXDesktopTouchBarUpgradedToTenTwelveOne" 1
defaults write "com.apple.finder" "FXDesktopVolumePositions" {
defaults write "com.apple.finder" "Backups of Jayvic\U2019s M1 MacBook Pro_0x1.53eeaf044faa5p+29" {
defaults write "com.apple.finder" "AnchorRelativeTo" 1
defaults write "com.apple.finder" "ScreenID" 0
defaults write "com.apple.finder" "xRelative" "-65"
defaults write "com.apple.finder" "yRelative" 78
defaults write "com.apple.finder" "Backups of Jayvic\U2019s MacBook Pro 1_0x1.53eeaf044faa5p+29" {
defaults write "com.apple.finder" "AnchorRelativeTo" 1
defaults write "com.apple.finder" "ScreenID" 0
defaults write "com.apple.finder" "xRelative" "-65"
defaults write "com.apple.finder" "yRelative" 78
defaults write "com.apple.finder" "Backups of Jayvic\U2019s MacBook Pro_0x1.53eeaf044faa5p+29" {
defaults write "com.apple.finder" "AnchorRelativeTo" 1
defaults write "com.apple.finder" "ScreenID" 0
defaults write "com.apple.finder" "xRelative" "-65"
defaults write "com.apple.finder" "yRelative" 78
defaults write "com.apple.finder" "Backups of Jayvic\U2019s MacBook Pro_0x1.6e4022bad3d26p+29" {
defaults write "com.apple.finder" "AnchorRelativeTo" 1
defaults write "com.apple.finder" "ScreenID" 0
defaults write "com.apple.finder" "xRelative" "-65"
defaults write "com.apple.finder" "yRelative" 190
defaults write "com.apple.finder" "Backups of Jayvic\U2019s MacBook Pro_0x1.6e403796632a6p+29" {
defaults write "com.apple.finder" "AnchorRelativeTo" 1
defaults write "com.apple.finder" "ScreenID" 0
defaults write "com.apple.finder" "xRelative" "-65"
defaults write "com.apple.finder" "yRelative" 190
defaults write "com.apple.finder" "ChatGPT Installer_0x1.6d9966ap+29" {
defaults write "com.apple.finder" "AnchorRelativeTo" 1
defaults write "com.apple.finder" "ScreenID" 0
defaults write "com.apple.finder" "xRelative" "-65"
defaults write "com.apple.finder" "yRelative" 78
defaults write "com.apple.finder" "Claude_0x1.6d37c6ap+29" {
defaults write "com.apple.finder" "AnchorRelativeTo" 1
defaults write "com.apple.finder" "ScreenID" 0
defaults write "com.apple.finder" "xRelative" "-65"
defaults write "com.apple.finder" "yRelative" 78
defaults write "com.apple.finder" "Cursor Installer_0x1.6ddb3a7p+29" {
defaults write "com.apple.finder" "AnchorRelativeTo" 1
defaults write "com.apple.finder" "ScreenID" 0
defaults write "com.apple.finder" "xRelative" "-65"
defaults write "com.apple.finder" "yRelative" 78
defaults write "com.apple.finder" "Discord_0x1.6cd8013p+29" {
defaults write "com.apple.finder" "AnchorRelativeTo" 1
defaults write "com.apple.finder" "ScreenID" 0
defaults write "com.apple.finder" "xRelative" "-65"
defaults write "com.apple.finder" "yRelative" 184
defaults write "com.apple.finder" "Google Chrome_0x1.6d71869p+29" {
defaults write "com.apple.finder" "AnchorRelativeTo" 1
defaults write "com.apple.finder" "ScreenID" 0
defaults write "com.apple.finder" "xRelative" "-65"
defaults write "com.apple.finder" "yRelative" 414
defaults write "com.apple.finder" "Raycast_0x1.6d7dae8p+29" {
defaults write "com.apple.finder" "AnchorRelativeTo" 1
defaults write "com.apple.finder" "ScreenID" 0
defaults write "com.apple.finder" "xRelative" "-65"
defaults write "com.apple.finder" "yRelative" 414
defaults write "com.apple.finder" "RunJS 3.1.0-universal_0x1.6da880c01545ep+29" {
defaults write "com.apple.finder" "AnchorRelativeTo" 1
defaults write "com.apple.finder" "ScreenID" 0
defaults write "com.apple.finder" "xRelative" "-65"
defaults write "com.apple.finder" "yRelative" 72
defaults write "com.apple.finder" "Telegram_0x1.6e1b2628p+29" {
defaults write "com.apple.finder" "AnchorRelativeTo" 1
defaults write "com.apple.finder" "ScreenID" 0
defaults write "com.apple.finder" "xRelative" "-65"
defaults write "com.apple.finder" "yRelative" 78
defaults write "com.apple.finder" "VLC media player_0x1.608d792p+29" {
defaults write "com.apple.finder" "AnchorRelativeTo" 1
defaults write "com.apple.finder" "ScreenID" 0
defaults write "com.apple.finder" "xRelative" "-65"
defaults write "com.apple.finder" "yRelative" 72
defaults write "com.apple.finder" "Warp_0x1.6d8b8dap+29" {
defaults write "com.apple.finder" "AnchorRelativeTo" 1
defaults write "com.apple.finder" "ScreenID" 0
defaults write "com.apple.finder" "xRelative" "-65"
defaults write "com.apple.finder" "yRelative" 414
defaults write "com.apple.finder" "Windsurf_0x1.6dd8c4ep+29" {
defaults write "com.apple.finder" "AnchorRelativeTo" 1
defaults write "com.apple.finder" "ScreenID" 0
defaults write "com.apple.finder" "xRelative" "-65"
defaults write "com.apple.finder" "yRelative" 78
defaults write "com.apple.finder" "Zed_0x1.6dde588728e12p+29" {
defaults write "com.apple.finder" "AnchorRelativeTo" 1
defaults write "com.apple.finder" "ScreenID" 0
defaults write "com.apple.finder" "xRelative" "-65"
defaults write "com.apple.finder" "yRelative" 78
defaults write "com.apple.finder" "Zed_0x1.6e1d26adf6317p+29" {
defaults write "com.apple.finder" "AnchorRelativeTo" 1
defaults write "com.apple.finder" "ScreenID" 0
defaults write "com.apple.finder" "xRelative" "-65"
defaults write "com.apple.finder" "yRelative" 78
defaults write "com.apple.finder" "superwhisper_0x1.5477ebca86cc1p+29" {
defaults write "com.apple.finder" "AnchorRelativeTo" 1
defaults write "com.apple.finder" "ScreenID" 0
defaults write "com.apple.finder" "xRelative" "-65"
defaults write "com.apple.finder" "yRelative" 78
defaults write "com.apple.finder" "FXDetachedDesktopProviderID" "com.apple.CloudDocs.iCloudDriveFileProvider/A3AE5FDC-7E94-431E-90E0-C93AB3418124"
defaults write "com.apple.finder" "FXDetachedDocumentsProviderID" "com.apple.CloudDocs.iCloudDriveFileProvider/A3AE5FDC-7E94-431E-90E0-C93AB3418124"
defaults write "com.apple.finder" "FXICloudDriveDesktop" 1
defaults write "com.apple.finder" "FXICloudDriveDocuments" 1
defaults write "com.apple.finder" "FXICloudDriveEnabled" 1
defaults write "com.apple.finder" "FXICloudLoggedIn" 1
defaults write "com.apple.finder" "FXPreferencesWindow.Location" "{{-2297, 603}, {377, 402}}"
defaults write "com.apple.finder" "FXPreferredSearchViewStyleVersion" "%00%00%00%01"
defaults write "com.apple.finder" "FXQuickActionsConfigUpgradeLevel" 3
defaults write "com.apple.finder" "FXRecentFolders" (
defaults write "com.apple.finder" "file-bookmark" {length 852, bytes 0x626f6f6b 54030000 00000410 30000000 ... 04000000 00000000 }
defaults write "com.apple.finder" "name" Petition
defaults write "com.apple.finder" "file-bookmark" {length 812, bytes 0x626f6f6b 2c030000 00000410 30000000 ... 04000000 00000000 }
defaults write "com.apple.finder" "name" "Mi Amore"
defaults write "com.apple.finder" "file-bookmark" {length 820, bytes 0x626f6f6b 34030000 00000410 30000000 ... 04000000 00000000 }
defaults write "com.apple.finder" "name" Shared
defaults write "com.apple.finder" "file-bookmark" {length 632, bytes 0x626f6f6b 78020000 00000410 30000000 ... 04000000 00000000 }
defaults write "com.apple.finder" "name" jayvicsanantonio
defaults write "com.apple.finder" "file-bookmark" {length 908, bytes 0x626f6f6b 8c030000 00000410 30000000 ... 04000000 00000000 }
defaults write "com.apple.finder" "name" "Evidence-of-Relationship"
defaults write "com.apple.finder" "file-bookmark" {length 912, bytes 0x626f6f6b 90030000 00000410 30000000 ... 04000000 00000000 }
defaults write "com.apple.finder" "name" "Passport-and-Travel-Document"
defaults write "com.apple.finder" "file-bookmark" {length 676, bytes 0x626f6f6b a4020000 00000410 30000000 ... 04000000 00000000 }
defaults write "com.apple.finder" "name" Downloads
defaults write "com.apple.finder" "file-bookmark" {length 760, bytes 0x626f6f6b f8020000 00000410 30000000 ... 04000000 00000000 }
defaults write "com.apple.finder" "name" "Driver License"
defaults write "com.apple.finder" "file-bookmark" {length 908, bytes 0x626f6f6b 8c030000 00000410 30000000 ... 04000000 00000000 }
defaults write "com.apple.finder" "name" "Proof-of-Intent-to-Marry"
defaults write "com.apple.finder" "file-bookmark" {length 908, bytes 0x626f6f6b 8c030000 00000410 30000000 ... 04000000 00000000 }
defaults write "com.apple.finder" "name" "K1 Visa Cover Letters"
defaults write "com.apple.finder" "FXSidebarUpgradedSharedSearchToTwelve" 1
defaults write "com.apple.finder" "FXSidebarUpgradedToTenFourteen" 1
defaults write "com.apple.finder" "FXSidebarUpgradedToTenTen" 1
defaults write "com.apple.finder" "FXSyncExtensionToolbarItemsPendingAdd" (
defaults write "com.apple.finder" "FXSyncExtensionToolbarItemsPendingRemove" (
defaults write "com.apple.finder" "FXToolbarUpgradedToTenEight" 1
defaults write "com.apple.finder" "FXToolbarUpgradedToTenNine" 2
defaults write "com.apple.finder" "FXToolbarUpgradedToTenSeven" 1
defaults write "com.apple.finder" "FavoriteTagNames" (
defaults write "com.apple.finder" "GoToField" 202
defaults write "com.apple.finder" "GoToFieldHistory" (
defaults write "com.apple.finder" "ICloudViewSettings" {
defaults write "com.apple.finder" "WindowState" {
defaults write "com.apple.finder" "ContainerShowSidebar" 1
defaults write "com.apple.finder" "ShowSidebar" 1
defaults write "com.apple.finder" "ShowStatusBar" 0
defaults write "com.apple.finder" "ShowTabView" 0
defaults write "com.apple.finder" "ShowToolbar" 1
defaults write "com.apple.finder" "WindowBounds" "{{505, 22}, {920, 464}}"
defaults write "com.apple.finder" "LastTrashState" 1
defaults write "com.apple.finder" "MeetingRoomViewSetting" {
defaults write "com.apple.finder" "CustomViewStyleVersion" 1
defaults write "com.apple.finder" "WindowState" {
defaults write "com.apple.finder" "ContainerShowSidebar" 1
defaults write "com.apple.finder" "ShowSidebar" 1
defaults write "com.apple.finder" "ShowStatusBar" 0
defaults write "com.apple.finder" "ShowTabView" 0
defaults write "com.apple.finder" "ShowToolbar" 1
defaults write "com.apple.finder" "WindowBounds" "{{214, 551}, {920, 464}}"
defaults write "com.apple.finder" "NSToolbar Configuration Browser" {
defaults write "com.apple.finder" "TB Display Mode" 2
defaults write "com.apple.finder" "TB Icon Size Mode" 1
defaults write "com.apple.finder" "TB Is Shown" 1
defaults write "com.apple.finder" "TB Size Mode" 1
defaults write "com.apple.finder" "NSWindow Frame GoToSheet" "202 797 460 180 0 0 1728 1079 "
defaults write "com.apple.finder" "NSWindow Frame GoToWindow" "634 674 460 180 0 0 1728 1079 "
defaults write "com.apple.finder" "NewWindowTarget" PfHm
defaults write "com.apple.finder" "PreferencesWindow.LastSelection" GNRL
defaults write "com.apple.finder" "PreviewPaneWidth" 250
defaults write "com.apple.finder" "RecentMoveAndCopyDestinations" (
defaults write "com.apple.finder" "RecentsArrangeGroupViewBy" "Date Last Opened"
defaults write "com.apple.finder" "SearchRecentsSavedViewStyleVersion" "%00%00%00%01"
defaults write "com.apple.finder" "SearchRecentsViewSettings" {
defaults write "com.apple.finder" "WindowState" {
defaults write "com.apple.finder" "ContainerShowSidebar" 1
defaults write "com.apple.finder" "ShowSidebar" 1
defaults write "com.apple.finder" "ShowStatusBar" 0
defaults write "com.apple.finder" "ShowTabView" 0
defaults write "com.apple.finder" "ShowToolbar" 1
defaults write "com.apple.finder" "WindowBounds" "{{404, 213}, {994, 725}}"
defaults write "com.apple.finder" "ShowExternalHardDrivesOnDesktop" 1
defaults write "com.apple.finder" "ShowHardDrivesOnDesktop" 0
defaults write "com.apple.finder" "ShowPathbar" 1
defaults write "com.apple.finder" "ShowPreviewPane" 0
defaults write "com.apple.finder" "ShowRecentTags" 0
defaults write "com.apple.finder" "ShowRemovableMediaOnDesktop" 1
defaults write "com.apple.finder" "ShowSidebar" 1
defaults write "com.apple.finder" "SidebarDevicesSectionDisclosedState" 1
defaults write "com.apple.finder" "SidebarPlacesSectionDisclosedState" 1
defaults write "com.apple.finder" "SidebarShowingSignedIntoiCloud" 1
defaults write "com.apple.finder" "SidebarShowingiCloudDesktop" 1
defaults write "com.apple.finder" "SidebarWidth" 139
defaults write "com.apple.finder" "SidebariCloudDriveSectionDisclosedState" 1
defaults write "com.apple.finder" "SmartSharedSearchViewSettings" {
defaults write "com.apple.finder" "WindowState" {
defaults write "com.apple.finder" "ContainerShowSidebar" 1
defaults write "com.apple.finder" "ShowSidebar" 1
defaults write "com.apple.finder" "ShowStatusBar" 0
defaults write "com.apple.finder" "ShowTabView" 0
defaults write "com.apple.finder" "ShowToolbar" 1
defaults write "com.apple.finder" "WindowBounds" "{{428, 337}, {920, 464}}"
defaults write "com.apple.finder" "StandardViewSettings" {
defaults write "com.apple.finder" "ExtendedListViewSettingsV2" {
defaults write "com.apple.finder" "calculateAllSizes" 0
defaults write "com.apple.finder" "columns" (
defaults write "com.apple.finder" "ascending" 1
defaults write "com.apple.finder" "identifier" name
defaults write "com.apple.finder" "visible" 1
defaults write "com.apple.finder" "width" 300
defaults write "com.apple.finder" "ascending" 0
defaults write "com.apple.finder" "identifier" dateModified
defaults write "com.apple.finder" "visible" 1
defaults write "com.apple.finder" "width" 181
defaults write "com.apple.finder" "ascending" 0
defaults write "com.apple.finder" "identifier" dateCreated
defaults write "com.apple.finder" "visible" 0
defaults write "com.apple.finder" "width" 181
defaults write "com.apple.finder" "ascending" 0
defaults write "com.apple.finder" "identifier" size
defaults write "com.apple.finder" "visible" 1
defaults write "com.apple.finder" "width" 97
defaults write "com.apple.finder" "ascending" 1
defaults write "com.apple.finder" "identifier" kind
defaults write "com.apple.finder" "visible" 1
defaults write "com.apple.finder" "width" 115
defaults write "com.apple.finder" "ascending" 1
defaults write "com.apple.finder" "identifier" label
defaults write "com.apple.finder" "visible" 0
defaults write "com.apple.finder" "width" 100
defaults write "com.apple.finder" "ascending" 1
defaults write "com.apple.finder" "identifier" version
defaults write "com.apple.finder" "visible" 0
defaults write "com.apple.finder" "width" 75
defaults write "com.apple.finder" "ascending" 1
defaults write "com.apple.finder" "identifier" comments
defaults write "com.apple.finder" "visible" 0
defaults write "com.apple.finder" "width" 300
defaults write "com.apple.finder" "ascending" 0
defaults write "com.apple.finder" "identifier" dateLastOpened
defaults write "com.apple.finder" "visible" 0
defaults write "com.apple.finder" "width" 200
defaults write "com.apple.finder" "ascending" 0
defaults write "com.apple.finder" "identifier" shareOwner
defaults write "com.apple.finder" "visible" 0
defaults write "com.apple.finder" "width" 200
defaults write "com.apple.finder" "ascending" 0
defaults write "com.apple.finder" "identifier" shareLastEditor
defaults write "com.apple.finder" "visible" 0
defaults write "com.apple.finder" "width" 200
defaults write "com.apple.finder" "iconSize" 16
defaults write "com.apple.finder" "showIconPreview" 1
defaults write "com.apple.finder" "sortColumn" name
defaults write "com.apple.finder" "extSize" 13
defaults write "com.apple.finder" "useRelativeDates" 1
defaults write "com.apple.finder" "viewOptionsVersion" 1
defaults write "com.apple.finder" "GalleryViewSettings" {
defaults write "com.apple.finder" "arrangeBy" name
defaults write "com.apple.finder" "iconSize" 48
defaults write "com.apple.finder" "showIconPreview" 1
defaults write "com.apple.finder" "viewOptionsVersion" 1
defaults write "com.apple.finder" "IconViewSettings" {
defaults write "com.apple.finder" "arrangeBy" none
defaults write "com.apple.finder" "backgroundColorBlue" 1
defaults write "com.apple.finder" "backgroundColorGreen" 1
defaults write "com.apple.finder" "backgroundColorRed" 1
defaults write "com.apple.finder" "backgroundType" 0
defaults write "com.apple.finder" "gridOffsetX" 0
defaults write "com.apple.finder" "gridOffsetY" 0
defaults write "com.apple.finder" "gridSpacing" 54
defaults write "com.apple.finder" "iconSize" 64
defaults write "com.apple.finder" "labelOnBottom" 1
defaults write "com.apple.finder" "showIconPreview" 1
defaults write "com.apple.finder" "showItemInfo" 0
defaults write "com.apple.finder" "extSize" 12
defaults write "com.apple.finder" "viewOptionsVersion" 1
defaults write "com.apple.finder" "ListViewSettings" {
defaults write "com.apple.finder" "calculateAllSizes" 0
defaults write "com.apple.finder" "columns" {
defaults write "com.apple.finder" "comments" {
defaults write "com.apple.finder" "ascending" 1
defaults write "com.apple.finder" "index" 7
defaults write "com.apple.finder" "visible" 0
defaults write "com.apple.finder" "width" 300
defaults write "com.apple.finder" "dateCreated" {
defaults write "com.apple.finder" "ascending" 0
defaults write "com.apple.finder" "index" 2
defaults write "com.apple.finder" "visible" 0
defaults write "com.apple.finder" "width" 181
defaults write "com.apple.finder" "dateLastOpened" {
defaults write "com.apple.finder" "ascending" 0
defaults write "com.apple.finder" "index" 8
defaults write "com.apple.finder" "visible" 0
defaults write "com.apple.finder" "width" 200
defaults write "com.apple.finder" "dateModified" {
defaults write "com.apple.finder" "ascending" 0
defaults write "com.apple.finder" "index" 1
defaults write "com.apple.finder" "visible" 1
defaults write "com.apple.finder" "width" 181
defaults write "com.apple.finder" "kind" {
defaults write "com.apple.finder" "ascending" 1
defaults write "com.apple.finder" "index" 4
defaults write "com.apple.finder" "visible" 1
defaults write "com.apple.finder" "width" 115
defaults write "com.apple.finder" "label" {
defaults write "com.apple.finder" "ascending" 1
defaults write "com.apple.finder" "index" 5
defaults write "com.apple.finder" "visible" 0
defaults write "com.apple.finder" "width" 100
defaults write "com.apple.finder" "name" {
defaults write "com.apple.finder" "ascending" 1
defaults write "com.apple.finder" "index" 0
defaults write "com.apple.finder" "visible" 1
defaults write "com.apple.finder" "width" 300
defaults write "com.apple.finder" "size" {
defaults write "com.apple.finder" "ascending" 0
defaults write "com.apple.finder" "index" 3
defaults write "com.apple.finder" "visible" 1
defaults write "com.apple.finder" "width" 97
defaults write "com.apple.finder" "version" {
defaults write "com.apple.finder" "ascending" 1
defaults write "com.apple.finder" "index" 6
defaults write "com.apple.finder" "visible" 0
defaults write "com.apple.finder" "width" 75
defaults write "com.apple.finder" "iconSize" 16
defaults write "com.apple.finder" "showIconPreview" 1
defaults write "com.apple.finder" "sortColumn" name
defaults write "com.apple.finder" "extSize" 13
defaults write "com.apple.finder" "useRelativeDates" 1
defaults write "com.apple.finder" "viewOptionsVersion" 1
defaults write "com.apple.finder" "SettingsType" StandardViewSettings
defaults write "com.apple.finder" "TagsCloudSerialNumber" 1
defaults write "com.apple.finder" "TrashViewSettings" {
defaults write "com.apple.finder" "CustomViewStyleVersion" 1
defaults write "com.apple.finder" "IconViewSettings" {
defaults write "com.apple.finder" "arrangeBy" dateAdded
defaults write "com.apple.finder" "backgroundColorBlue" 1
defaults write "com.apple.finder" "backgroundColorGreen" 1
defaults write "com.apple.finder" "backgroundColorRed" 1
defaults write "com.apple.finder" "backgroundType" 0
defaults write "com.apple.finder" "gridOffsetX" 0
defaults write "com.apple.finder" "gridOffsetY" 0
defaults write "com.apple.finder" "gridSpacing" 54
defaults write "com.apple.finder" "iconSize" 64
defaults write "com.apple.finder" "labelOnBottom" 1
defaults write "com.apple.finder" "scrollPositionX" 0
defaults write "com.apple.finder" "scrollPositionY" 0
defaults write "com.apple.finder" "showIconPreview" 1
defaults write "com.apple.finder" "showItemInfo" 0
defaults write "com.apple.finder" "extSize" 12
defaults write "com.apple.finder" "viewOptionsVersion" 1
defaults write "com.apple.finder" "WindowState" {
defaults write "com.apple.finder" "ContainerShowSidebar" 1
defaults write "com.apple.finder" "ShowSidebar" 1
defaults write "com.apple.finder" "ShowStatusBar" 0
defaults write "com.apple.finder" "ShowTabView" 0
defaults write "com.apple.finder" "ShowToolbar" 1
defaults write "com.apple.finder" "WindowBounds" "{{204, 139}, {920, 464}}"
defaults write "com.apple.finder" "_FXSortFoldersFirst" 1
defaults write "com.apple.finder" "_FXSortFoldersFirstOnDesktop" 1

# com.apple.desktopservices settings

defaults write "com.apple.desktopservices" "DSDontWriteNetworkStores" 1
defaults write "com.apple.desktopservices" "DSDontWriteUSBStores" 1

# Apply changes by restarting affected services
killall Finder
killall Dock
killall SystemUIServer
